### ISSUE TITLE
Destroys m4a files

### ISSUE THREAD

**Issue by 0x00A** [egoroof/browser-id3-writer#23]
Works fine on mp3 files, but m4a files are no longer playable after writing, any ideas?

**Comment by egoroof** [comment]
Could you please send me a sample of m4a file, please? I'll then check the reason

**Comment by 0x00A** [comment]
Sent you a dropbox invite. I haven't looked at the m4a format yet (i see that someone has written a [`parser`](https://www.npmjs.com/package/mp4js) i wonder how hard it would be to write `m4a`/`mp4`s.

**Comment by 0x00A** [comment]
Also, i just saw this -- https://github.com/uupaa/MP4.js

**Comment by 0x00A** [comment]
heh, ok, i found this -- https://www.npmjs.com/package/mp4edit, maybe roll it into this lib :)

**Comment by egoroof** [comment]
> Works fine on mp3 files, but m4a files are no longer playable after writing, any ideas?

It only will work with mp3 files. Because m4a files have different tag format (not ID3). So I guess I'll add checking in the library so it will throw an exception when it takes not mp3 file.

**Comment by 0x00A** [comment]
perfect!

**Comment by Jobians** [comment]
???
