### ISSUE TITLE
Support nodejs

### ISSUE THREAD

**Issue by delold** [egoroof/browser-id3-writer#35]
As of today, there aren't any pure JS IDv3 writers for nodejs. It would be very great if it worked for nodejs.

This would probably require a support for Buffer instead of ArrayBuffer and a [polyfill](https://github.com/inexorabletash/text-encoding) for TextEncoder.

**Comment by egoroof** [comment]
> there aren't any pure JS IDv3 writers for nodejs

Have you seen https://github.com/Zazama/node-id3 and https://github.com/interbred-monkey/id3_reader? It seems they both supports writing ID3 in pure js.

**Comment by delold** [comment]
Thanks! Still, it would be cool to have a library working both on browser / node (close if necessary).

**Comment by egoroof** [comment]
It will work with nodejs 4+ soon. Guess in 2.3.0.
TextEncoder is no longer needed (#36).
Buffer is working well with ArrayBuffer. They efficiently shares the memory with each other.
I'll add example after releasing.

**Comment by egoroof** [comment]
2.3.0 is here. See example in [readme](https://github.com/egoroof/browser-id3-writer#nodejs-1).
