### ISSUE TITLE
Any supports for frame COMM?

### ISSUE THREAD

**Issue by awsp** [egoroof/browser-id3-writer#38]
Hi, I tried to write a comment into the tag but receive this error. 

```
browser-id3-writer.js:283
	                        throw new Error('Unsupported frame ' + frameName);
	                        ^

Error: Unsupported frame COMM
```

I know COMM isn't in the supported frame, but will there any supports in the future?

**Comment by egoroof** [comment]
Hi!
Yeah, I will add it soon.

**Comment by awsp** [comment]
Thanks! Looking forward to that.

**Comment by egoroof** [comment]
I've [released v3](https://github.com/egoroof/browser-id3-writer/releases/tag/v3.0.0) and COMM is available now!

**Comment by awsp** [comment]
Thanks!
Happy holidays!

**Comment by egoroof** [comment]
🎅 you too!
