### ISSUE TITLE
Stream support (ReadableStream)

### ISSUE THREAD

**Issue by berstend** [egoroof/browser-id3-writer#41]
Hey there, great code!

I was wondering if it'd be possible to use a `ReadableStream` instead of `ArrayBuffer` to modify the MP3 while it's being fetched from the remote host and being passed to the client.

Chrome ships support for streaming response bodies already:
https://www.chromestatus.com/feature/5804334163951616

What are your thoughts on this? :-)

**Comment by egoroof** [comment]
Hello and thanks for the issue.

At the current moment you can create ID3Writer from empty arrayBuffer and then concat it manually with any bytes.

For example:

```js
const writer = new ID3Writer(new ArrayBuffer(0));
writer.padding = 0; // default 4096
writer.setFrame('TIT2', 'Home'); // set any tags here
writer.addTag();
const id3Tag = writer.arrayBuffer;
```

Then concat `id3Tag` with your stream when you need it. But in this case it wont remove old tag (if it exist).

But yes, I'm looking ahead and think how to improve the lib. I guess it will be divided into two stages:

1. tag creation (without song) - it's possible now, but it can be simplified
2. using lib helpers to remove old tag and append a new one to any buffer (including streams)

Any thoughts are welcome.

**Comment by egoroof** [comment]
It would be great if you share how you use ReadableStream nowadays (while there is no WritableSteam).

**Comment by berstend** [comment]
Thank you for your insightful comment. :-)

I made some progress using a Service Worker with a `fetch` proxy and constructing a new `ReadableStream` there, where I would enqueue the new chunks of data I `fetch` there:

```js
this.addEventListener('fetch', event => {
  var stream = new ReadableStream({
    start(controller) {

      fetch(MP3_URL).then(response => {
        var reader = response.body.getReader();
        var bytesReceived = 0;

        reader.read().then(function processResult(result) {
          if (result.done) {
            console.debug("Fetch complete");
            controller.close();
            return;
          }
          controller.enqueue(
            result.value
          );

          bytesReceived += result.value.length;
          console.debug('Received', bytesReceived, 'bytes of data so far');

          // Read some more, and call this function again
          return reader.read().then(processResult);
        });
      });

    } // start
  });

  event.respondWith(new Response(stream, {
    headers: {'Content-Type': 'audio/mpeg', 'Content-disposition': 'attachment; filename=stream.mp3'}
  }));
});
```

My naive attempts at concatenating the ID3Writer data at position 4096 failed, but it should work in theory (I had issues finding the right spot and converting the arrayBufer to an Uint8Array correctly). 😅 

Right now I'm trying to figure out if `chrome.download.downloads` supports a streaming response, they do support Blobs (I stumbled across a Mozilla issue comment from you while researching this 😄) but I don't think I can properly convert the `ReadableStream` to "streaming blob data" here.

My use-case is similar to your Yandex Fisher extension so I most likely stick with what already works (XHR + buffering + ID3Writer + chrome.downloads) for now.

But It'd be great to have a completely streaming based solution in the future, making use of the multi-threaded `chrome.downloads` as well. :-)

Keep up the good work!

**Comment by egoroof** [comment]
> converting the arrayBufer to an Uint8Array correctly

`new Uint8Array(ArrayBuffer)` is it correctly ?)

> I most likely stick with what already works 

[WritableStream is coming](https://www.chromestatus.com/feature/5928498656968704)

> making use of the multi-threaded chrome.downloads as well

yeah, that will cool, I wait it too

> Keep up the good work

thanks!

**Comment by egoroof** [comment]
Ok, I've added a demo with Id3Writer and stream: [https://egoroof.ru/browser-id3-writer/stream](https://egoroof.ru/browser-id3-writer/stream). It uses [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js) library. Looks like it just downloads a song with id3 tag from server, but if you follow the url of the song you'll see there is no id3 tag there :)

That's all the code:

```js
const url = 'https://raw.githubusercontent.com/egoroof/egoroof.github.io/master/unicorns/audio/daft_punk_get_lucky.mp3';
const songSize = 4509696;

const id3Writer = new ID3Writer(new ArrayBuffer(0));
id3Writer.setFrame('TIT2', 'Home')
    .setFrame('TPE1', ['Eminem', '50 Cent'])
    .setFrame('TALB', 'Friday Night Lights')
    .setFrame('TYER', 2004)
    .setFrame('TRCK', '6/8')
    .setFrame('TCON', ['Soundtrack']);
id3Writer.addTag();
const id3Tag = new Uint8Array(id3Writer.arrayBuffer);

document.getElementById('start').addEventListener('click', function () {
    fetch(url).then(response => {
        const fileStream = streamSaver.createWriteStream('daft_punk_get_lucky.mp3', songSize + id3Tag.byteLength);
        const writer = fileStream.getWriter();
        const reader = response.body.getReader();

        // push id3 tag first
        writer.write(id3Tag).then(pump).then(() => console.log('All done'));

        function pump() {
            return reader.read().then(result => {
                if (result.done) {
                    return writer.close();
                } else {
                    return writer.write(result.value).then(pump);
                }
            });
        }
    });
});
```

So I think I can answer to your question now:

> I was wondering if it'd be possible to use a ReadableStream instead of ArrayBuffer to modify the MP3 while it's being fetched from the remote host and being passed to the client.

![1450197206_busted 1](https://cloud.githubusercontent.com/assets/2605831/25242116/bbacb218-2622-11e7-9424-faadbefa3645.jpg)

Still if you have any ideas you are welcome :)

**Comment by berstend** [comment]
Great stuff @egoroof - thanks!  :) 👍
