### ISSUE TITLE
Synchronized lyrics

### ISSUE THREAD

**Issue by trustedtomato** [egoroof/browser-id3-writer#44]
Can I set synchronized lyrics? Or is it planned?

**Comment by egoroof** [comment]
Currently you can't set synchronized lyrics (it isn't supported). Can you please describe your usage case. I mean how will you set time stamps? Manually? Or there are some programs which breaks song text by its usage time?

**Comment by trustedtomato** [comment]
Manually. An example of the object would be
```javascript
[
    {milliseconds: 6370, line: 'Dog goes "woof"'},
    {milliseconds: 9560, line: 'Cat goes "meow"'}
    …
]
```

It could be from a .lrc file, a SYLT Editor or an online database (mine is the latter).

**Comment by trustedtomato** [comment]
And maybe duration of the line could be specified too with the duration property like
```javascript
[
    {duration: 3520, milliseconds: 16560, line: 'I could lift you up'},
    {duration: 2550, milliseconds: 20080 line: 'I could show you what you want to see'}
    {duration: 2750, milliseconds: 25430 line: 'And take you where you want to be'}
    {line: ''} // paragraph end
    …
]
```

**Comment by J05HI** [comment]
@egoroof 
This would be amazing!!!
