### ISSUE TITLE
Add support for ReplayGain tags

### ISSUE THREAD

**Issue by FatKiwi** [egoroof/browser-id3-writer#47]
![snap80](https://user-images.githubusercontent.com/9163913/34381507-cc552e62-eb00-11e7-8e32-c5780db77808.jpg)

Or should TXXX be used?

**Comment by egoroof** [comment]
Yeah, you should use `TXXX` frames for this. See http://wiki.hydrogenaud.io/index.php?title=ReplayGain_specification#ID3v2 for details

It would be something like this:

```js
writer.setFrame('TXXX', {
    description: 'REPLAYGAIN_TRACK_GAIN',
    value: '-9.49 dB'
});
```

**Comment by FatKiwi** [comment]
Thanks, got it!
