### ISSUE TITLE
Document Edit

### ISSUE THREAD

**Issue by GoelBiju** [egoroof/browser-id3-writer#49]
Hi,

Sorry to disturb and I am quite new to NodeJS, I was recently using this library to write ID3 tags. I noticed that in the documents regarding the library it says an ArrayBuffer is expected as the initial value for the Writer and I was not aware that a normal Buffer could be also provided until I had a look at the code in the ID3Writer.js file.

Would it be possible to change it to say that Buffer is also allowed as well as ArrayBuffer? Reading other articles and pages it states that this is the standard now? I don't know if this is the case, if it is not sorry for this issue.

Thank you for your work! :)

**Comment by egoroof** [comment]
Hello,

This library works both nodejs and browsers. In browsers there's no `Buffer`.

In the readme there's a nodejs section with examples provided https://github.com/egoroof/browser-id3-writer#nodejs. They are using `Buffer`.

I've made a small change to readme that I think would be helpful https://github.com/egoroof/browser-id3-writer/commit/4924f58b57cc9a0889e0aa338d489fb919f0662e

You you have more places to update, please send a PR.
Thanks!

**Comment by GoelBiju** [comment]
Thank you @egoroof , I appreciate the work. It works brilliantly!
