### ISSUE TITLE
writing tags increases file size much larger than needed

### ISSUE THREAD

**Issue by nikmartin** [egoroof/browser-id3-writer#57]
if I write 7 tags into the smallest possible mp3 (72 bytes), the output file is > 4k. If I write the same tags using other libraries, the file is ~362 bytes.  Attached are two files, one written by your library, and one written by kid3. Looking at both files in a hex editor, your library adds 4096 null bytes between the ID3 header and the first Mp3 frame.

I see at: https://github.com/egoroof/browser-id3-writer/blob/master/src/ID3Writer.js#L109 that a 4k buffer is added to the ID3 header when being written. 

[tracks.zip](https://github.com/egoroof/browser-id3-writer/files/2319516/tracks.zip)

**Comment by egoroof** [comment]
This is called "padding" - null bytes before song data which allows you to add later more tags faster http://id3.org/id3guide#Padding

You can disable padding like this:
```js
const writer = new ID3Writer(arrayBuffer);
writer.padding = 0;
writer.setFrame('TIT2', 'Home');
writer.addTag();
```
