### ISSUE TITLE
MP4s?

### ISSUE THREAD

**Issue by FPChris** [egoroof/browser-id3-writer#59]
MP4 videos seems to fail. MP3's worked fine.

**Comment by egoroof** [comment]
MP4 has other tag format, not ID3 (this library only write ID3 tag)

**Comment by GrayGalaxy** [comment]
M4A files are also failed. Is it because M4A and MP4 are of same type

**Comment by AHOHNMYC** [comment]
And what behavior you expected? It is normal reaction on [different tag format](https://mutagen.readthedocs.io/en/latest/api/mp4.html).
