### ISSUE TITLE
Key Tag should accept alphanumerical values

### ISSUE THREAD

**Issue by ethaning** [egoroof/browser-id3-writer#61]
Key tag frame currently only accepts traditionally written keys (A, C#, etc..)

Many softwares (e.g. DJ Softwares such as Traktor, Serato) express musical keys with open key notation. Example can be found here: https://mixedinkey.com/harmonic-mixing-guide/

The regex should be changed to allow alphanumerical key values, such as 12A, 4B, 2m, 2, ...

**Comment by egoroof** [comment]
Validation removed in v4.2.0
