### ISSUE TITLE
USLT and COMM frames don't allow entry of langage codes other than English

### ISSUE THREAD

**Issue by MrNope** [egoroof/browser-id3-writer#62]
Text fields such as USLT and COMM currently save a three digit language code, as per the ID3 spec, but this is hardcoded to `eng`:
https://github.com/egoroof/browser-id3-writer/blob/0bfdf0d1d7a14516389685895acbf0381054c89e/src/ID3Writer.js#L229
https://github.com/egoroof/browser-id3-writer/blob/0bfdf0d1d7a14516389685895acbf0381054c89e/src/ID3Writer.js#L304
Can support please be added to allow this value to be passed though along with the other parameters?
Thanks.

**Comment by egoroof** [comment]
Support was added in v4.4.0! Example:

```
writer.setFrame('USLT', {
  language: 'jpn',
  description: '例えば',
  lyrics: 'サマータイム'
});
```
