### ISSUE TITLE
Can't let me Add meta in Protected files.

### ISSUE THREAD

**Issue by technoknol** [egoroof/browser-id3-writer#70]
I have some files which shows Nothing in **Protected**, and in few files **Protected = No**. 

Those with **NO** I can add meta, but not in other files. Check screenshot , and one protected file. 

**Screenshot:**
![image](https://user-images.githubusercontent.com/6429418/73683575-7e16c580-46e8-11ea-9810-70b53689b51b.png)

**Protected MP3 file (MP3 not supported, uploading ZIP):** [Padi Padi Leche 320 Kbps.zip](https://github.com/egoroof/browser-id3-writer/files/4149725/Padi.Padi.Leche.320.Kbps.zip)

**Comment by AHOHNMYC** [comment]
[ffprobe](https://ffmpeg.org/ffprobe.html#Description) says it is [`aac`](https://en.wikipedia.org/wiki/Advanced_Audio_Coding) renamed to `.mp3`
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Padi Padi Leche 320 Kbps.mp3':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.82.101
  Duration: 00:03:23.80, start: 0.000000, bitrate: 323 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 322 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

**Comment by technoknol** [comment]
@AHOHNMYC  Nice catch thanks. 
So does it mean that I can't edit this file ? be it aac or mp3 ?

**Comment by AHOHNMYC** [comment]
@technoknol yes, you cannot edit this file using `browser-id3-writer`. But [some](https://aimp.ru) [players](https://foobar2000.org/FAQ#tagging_files) and [special](https://xdlab.ru/en) [tag-editting](https://github.com/Martchus/tageditor) [utilites](https://mp3tag.de/en) are able to do this.

`ffprobe` said, file contains `aac` in `mp4a`. File extension does not reflect *real* file content.
e.g. file renamed from `foo.mp3` to `bar.opus` still contains data in mp3 format.

If you are interested in investigating and editing tags, check out [this](https://sourceforge.net/projects/audiotools/files/audio%20formats%20reference/2.20/audioformats-2.22-a4.pdf/download).

**Comment by egoroof** [comment]
@AHOHNMYC thx for figuring this out
