### ISSUE TITLE
stream demo browser support

### ISSUE THREAD

**Issue by dimaqq** [egoroof/browser-id3-writer#74]
I've tried https://egoroof.ru/browser-id3-writer/stream out of interest for `respondWith` API...

* chrome works
* firefox kinda works (downloads .part file, fails to rename? or download is incomplete?)
* firefox nightly doesn't work (page says feature not supported)
* safari doesn't work (downloads html instead)
* safari TP doesn't work (same)

Tested on macOS 11.1 (intel).
I understand safari issues, as the API is not supported per caniuse.com, but firefox breakage is odd...

**Comment by egoroof** [comment]
Could you check it again? I've updated dependencies (web-streams-polyfill and streamsaver) which response for it.

Also the demo moved to the new host: https://egoroof.github.io/browser-id3-writer/stream.html

**Comment by dimaqq** [comment]
Hi, sorry I’ve moved on to other projects.
