### ISSUE TITLE
TIT 1 is not supported

### ISSUE THREAD

**Issue by riosant** [egoroof/browser-id3-writer#79]
TIT1 is not supported

Uncaught Error: Unsupported frame TIT1 at t.setFrame (browser-id3-writer.js:1:4487) at FileReader.reader.onload (track-uploader.js:18:30)

writer.setFrame('TIT1', 'MP3 TAGGED SONG');

**Comment by egoroof** [comment]
what version of the library do you use?

**Comment by egoroof** [comment]
TIT1 was added since [v4.3.0](https://github.com/egoroof/browser-id3-writer/releases/tag/v4.3.0) version, so you should update the lib
