### ISSUE TITLE
[Feature Request] Support for AAC or M4A files?

### ISSUE THREAD

**Issue by mubaid** [egoroof/browser-id3-writer#85]
The current library works correctly on mp3 files. But fails on AAC or M4A files that have their headers differently.
Currently there is no library in JS that works with AAC or M4A files.

Any plans on adding this feature?

**Comment by egoroof** [comment]
> But fails on AAC or M4A files that have their headers differently.

This library only works with ID3 tag, not other media tags. It has that desription:

> JavaScript library for writing ID3 tag to MP3 files in browsers and Node.js

Why did you decide it should work with AAC or M4A?

**Comment by Jobians** [comment]
Why close
