### ISSUE TITLE
How do I add empty id3 buffer to my mp3 buffer

### ISSUE THREAD

**Issue by 4rvx** [egoroof/browser-id3-writer#88]
You can also create only ID3 tag without song and use it as you want:
```js
const writer = new ID3Writer(Buffer.alloc(0));
writer.padding = 0; // default 4096
writer.setFrame('TIT2', 'Home');
writer.addTag();
const id3Buffer = Buffer.from(writer.arrayBuffer);
```

How do I add empty id3 buffer to my mp3 buffer?

**Comment by egoroof** [comment]
[Buffer.concat](https://nodejs.org/dist/latest-v20.x/docs/api/buffer.html#static-method-bufferconcatlist-totallength)

**Comment by 4rvx** [comment]
i was using mp4 files instead of mp3 files causing the issue
